### ISSUE TITLE
你好，你的这个运行不了呀

### ISSUE THREAD

**Issue by james1kobby** [cagik/trajectoryOpt#1]

**Comment by cagik** [comment]
这个仓库很久没有维护了，程序里面需要传入的数据我没有上传。更易于阅读学习的请参照https://github.com/libai1943/CartesianPlanner

**Comment by cagik** [comment]
请参照https://github.com/crvs/KDTree

**Comment by james1kobby** [comment]
谢谢哈，我去学习一下哎
